name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1.8.0

    - name: Compile
      run: |
         cl /EHsc /O2 /DNDEBUG /Fe:leetcode_build.exe leetcode\main.cpp leetcode\CommonFunction.cpp leetcode\RemovElement.cpp leetcode\RemoveDuplicatesSortedArray.cpp leetcode\RemoveLinkedListElement.cpp leetcode\ReverseString.cpp leetcode\SingleNumber.cpp
