name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Print basic system info
      run: |
        echo "Printing system info..."
        uname -a
        echo "C++ compiler version:"
        g++ --version
        echo "Current directory:"
        pwd
        echo "Environment variables:"
        env
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++
    - name: Build
      run: |
        g++ -o myapp main.cpp
    - name: Run
      run: ./myapp
