name: C++ CI  # 定义工作流名称

on:  # 触发条件
  push:  # 推送事件
    branches: [ main ]  # 仅对main分支生效
  pull_request:  # 拉取请求事件
    branches: [ main ]  # 仅对main分支生效

jobs:
  build:  # 工作名称
    runs-on: windows-latest  # 运行环境

    steps:
    - uses: actions/checkout@v2  # 检出代码

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
    
    - name: Compile with MSVC
      run: cmd /c "cl /EHsc /Fe:leetcode_build.exe leetcode\main.cpp leetcode\CommonFunction.cpp leetcode\RemovElement.cpp leetcode\RemoveDuplicatesSortedArray.cpp leetcode\RemoveLinkedListElement.cpp leetcode\ReverseString.cpp leetcode\SingleNumber.cpp"
      shell: cmd
    
    - name: Upload executable as artifact
      uses: actions/upload-artifact@v2
      with:
          name: leetcode-build
          path: leetcode_build.exe
